local grid_sizes = {
  "4x4",
  "6x4",
  "6x6",
  "8x4",
  "8x6",
  "8x8",
  "10x4",
  "10x6",
  "10x8",
  "10x10",
  "12x4",
  "12x6",
  "12x8",
  "12x10",
}

data:extend({
  {
    type = "string-setting",
    name = "VehicleGrid-car",
    order = "aa",
    setting_type = "startup",
    default_value = "8x6",
    allowed_values = grid_sizes,
  },
  {
    type = "string-setting",
    name = "VehicleGrid-tank",
    order = "ab",
    setting_type = "startup",
    default_value = "10x8",
    allowed_values = grid_sizes,
  },
  {
    type = "string-setting",
    name = "VehicleGrid-spider",
    order = "ac",
    setting_type = "startup",
    default_value = "10x10",
    allowed_values = grid_sizes,
  },
  {
    type = "string-setting",
    name = "VehicleGrid-loco",
    order = "ba",
    setting_type = "startup",
    default_value = "10x8",
    allowed_values = grid_sizes,
  },
  {
    type = "string-setting",
    name = "VehicleGrid-wagon",
    order = "bb",
    setting_type = "startup",
    default_value = "10x6",
    allowed_values = grid_sizes,
  },
  {
    type = "string-setting",
    name = "VehicleGrid-artillery-wagon",
    order = "bd",
    setting_type = "startup",
    default_value = "10x6",
    allowed_values = grid_sizes,
  },
  {
    type = "bool-setting",
    name = "VehicleGrid-automatic_mode-bots",
    order = "ca",
    setting_type = "startup",
    default_value = true,
  },
  {
    type = "string-setting",
    name = "VehicleGrid-override-grids",
    order = "cb",
    setting_type = "startup",
    default_value = "override-base",
    allowed_values = {"off", "update-size", "override-base", "override-all"}
  },
})